### ISSUE TITLE
New release on PyPI

### ISSUE THREAD

**Issue by mkai** [coolbho3k/manuf#15]
Hi,

thanks for this tool! After the manuf file format change, would it be possible to get a new release with the new parser published to PyPI?

**Comment by neil-orans** [comment]
I just made a PR for this. Hopefully @coolbho3k can do this soon.

**Comment by veeshi** [comment]
Any update with this @coolbho3k?

**Comment by tristanlatr** [comment]
Hello, I'll do that in the next couple days ;)
