### ISSUE TITLE
Failed to connect - Has URL permission changed to OUI Database?

### ISSUE THREAD

**Issue by T2evh** [coolbho3k/manuf#28]
A working program, which I've not amended now fails. Has permission to the OUI database changed to deny access?

mac_addr_test.py", line 37, in <module>
    p = manuf.MacParser(update=True)
manuf.py", line 70, in __init__
    self.update()
manuf.py", line 146, in update
    raise URLError("Failed downloading OUI database")
urllib.error.URLError: <urlopen error Failed downloading OUI database>

**Comment by codeswhite** [comment]
I have tried to reprocduce the error and it didn't happened on my machine, everything worked.
The script attempt to download the update from the following URL:
`https://code.wireshark.org/review/gitweb?p=wireshark.git;a=blob_plain;f=manuf`
Which (for connection test purpose) can be shortened to the domain itself:
`https://code.wireshark.org/`
So you apparently unable to connect to this domain for some reason.

**Comment by T2evh** [comment]
Thanks for investigating. It's fixed now but I'm not sure of the cause. Some of the manuf functionality worked prior to the fix. I had to reinstall Cisco Umbrella client on my laptop. It does URL filtering. I suspect it was somehow blocking the lookup. 

Again thanks very much for taking the time to investigate
