### ISSUE TITLE
Wireshark file format change

### ISSUE THREAD

**Issue by anyone2** [coolbho3k/manuf#7]
The formatting of the wireshark.org file appears to have changed. Previously it used “ # “ as a separator for the full manufacturer name and a comment.

The file now appears to use “ # “ solely as a comment and as a result, after you update the manuf file from Wireshark's git, only true comments are displayed.

```
python manuf.py 08:00:89
Vendor(manuf=u'Kinetics', comment=u'Kinetics\t\t\tAppleTalk-Ethernet interface')

python manuf.py 1C:BD:B9:FF:E9:18
Vendor(manuf=u'D-LinkIn', comment=u'D-Link International')

python manuf.py D8:FC:93
Vendor(manuf=u'IntelCor', comment=u'Intel Corporate')

python manuf.py 00:40:1C
Vendor(manuf=u'AstPenti', comment=u'AST\t\t\t\tPentium/90 PC (emulating AMD EISA card)')

```

After update

```
python manuf.py --update
python manuf.py 08:00:89
Vendor(manuf=u'Kinetics', comment=u'AppleTalk-Ethernet interface')
python manuf.py 1C:BD:B9:FF:E9:18
Vendor(manuf=u'D-LinkIn', comment=None)
python manuf.py D8:FC:93
Vendor(manuf=u'IntelCor', comment=None)
python manuf.py 00:40:1C
Vendor(manuf=u'AstPenti', comment=u'Pentium/90 PC (emulating AMD EISA card)')
```

**Comment by tristanlatr** [comment]
Seems that this issue can be closed as the PR as been merged ?

**Comment by anyone2** [comment]
Thanks for officially closing this out. The email notification prompted me to review this issue from 2017 and then notice, that a forked and maintained version of this library is at https://github.com/daniel-leicht/manuf-ng

**Comment by tristanlatr** [comment]
Hello,

Thanks for the updated fork but this repo is now back to life !

We are now tree people to have edits rights so less chances that we all disappear and leave the repos alone.
